// <auto-generated />
using System;
using AgroindustryManagementWeb.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroindustryManagementWeb.Migrations
{
    [DbContext(typeof(AGDatabaseContext))]
    [Migration("20251123224619_Machine")]
    partial class Machine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Area")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Culture")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WorkDuralityPerHectare")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Machines", (string)null);
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CultureType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FertilizerPerHectare")
                        .HasColumnType("REAL");

                    b.Property<double>("SeedPerHectare")
                        .HasColumnType("REAL");

                    b.Property<double>("WorkerPerHectare")
                        .HasColumnType("REAL");

                    b.Property<double>("WorkerWorkDuralityPerHectare")
                        .HasColumnType("REAL");

                    b.Property<double>("Yield")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Resources", (string)null);
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.WorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstimatesEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("RealEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerTasks", (string)null);
                });

            modelBuilder.Entity("FieldWorker", b =>
                {
                    b.Property<int>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FieldId", "WorkersId");

                    b.HasIndex("WorkersId");

                    b.ToTable("FieldWorker");
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.InventoryItem", b =>
                {
                    b.HasOne("AgroindustryManagementWeb.Models.Warehouse", "Warehouse")
                        .WithMany("InventoryItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Machine", b =>
                {
                    b.HasOne("AgroindustryManagementWeb.Models.Field", "Field")
                        .WithMany("Machines")
                        .HasForeignKey("FieldId");

                    b.HasOne("AgroindustryManagementWeb.Models.Resource", "Resource")
                        .WithMany("RequiredMachines")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.WorkerTask", b =>
                {
                    b.HasOne("AgroindustryManagementWeb.Models.Field", "Field")
                        .WithMany("Tasks")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroindustryManagementWeb.Models.Worker", "Worker")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FieldWorker", b =>
                {
                    b.HasOne("AgroindustryManagementWeb.Models.Field", null)
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroindustryManagementWeb.Models.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Field", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Resource", b =>
                {
                    b.Navigation("RequiredMachines");
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Warehouse", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("AgroindustryManagementWeb.Models.Worker", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
